### PR TITLE
Bugfix: Boto3 upgrade

### PR DESCRIPTION
**Pull request by sebdah**
Fixes for the boto3 upgrade.

### CODE REVIEW

**Comment by sebdah** [comment]
@przemyslaw-elias I have released this version with the dependency fix as `0.10.1b1`, could you please give that one a try?

**Comment by sebdah** [comment]
Ref #32

**Comment by przemyslaw-elias** [comment]
Our old distro runs python2.7 :) It can't find ec2-metadata v.2.2.0.

```
Collecting ec2-metadata>=2.2.0 (from aws-ec2-assign-elastic-ip==0.10.1b1)
  Could not find a version that satisfies the requirement ec2-metadata>=2.2.0 (from aws-ec2-assign-elastic-ip==0.10.1b1) (from versions: 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.7.1, 1.8.0)
No matching distribution found for ec2-metadata>=2.2.0 (from aws-ec2-assign-elastic-ip==0.10.1b1)
```

**Comment by sebdah** [comment]
Which version of `ec2-metadata` is available to you?

I find 2.2.0 with my Python 2.7:

```
⟩ pip2 search ec2-metadata | grep ec2-metadata                                                                       [09:24:10]
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ec2-metadata (2.2.0)                                      - An easy interface to query the EC2 metadata API, with caching.
```

**Comment by przemyslaw-elias** [comment]
`1.8.0`

**Comment by sebdah** [comment]
Cool, I released 0.10.1b2 with 1.8.0 as a dependency instead.

**Comment by przemyslaw-elias** [comment]
I've still got:

```
Traceback (most recent call last):
  File "/usr/local/bin/aws-ec2-assign-elastic-ip", line 31, in <module>
    aws_ec2_assign_elastic_ip.main()
  File "/usr/local/lib/python2.7/site-packages/aws_ec2_assign_elastic_ip/__init__.py", line 59, in main
    address = _get_unassociated_address()
  File "/usr/local/lib/python2.7/site-packages/aws_ec2_assign_elastic_ip/__init__.py", line 115, in _get_unassociated_address
    all_addresses = connection.get_all_addresses()
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 601, in __getattr__
    self.__class__.__name__, item)
```
It still needs migrating line 115 from `connection.get_all_addresses `connection.describe_addresses`.

**Comment by sebdah** [comment]
Sure, I'll take a look at that too :+1:

**Comment by sebdah** [comment]
@przemyslaw-elias I have moved over to `describe_addresses` and converted that part of the code to work with Boto3. It's released as 0.10.1b3

**Comment by sebdah** [comment]
Awesome, I'll get it merged now then. 

Thanks for the help @przemyslaw-elias!

**Comment by sebdah** [comment]
Released :heavy_check_mark:

**Comment by przemyslaw-elias** [comment]
I'm now getting: 😱 

```
pip install aws-ec2-assign-elastic-ip
Collecting aws-ec2-assign-elastic-ip
  Downloading https://files.pythonhosted.org/packages/85/47/99d6c6dc1e729467725691f41a19b7f7ddf08c3c1657ad69f8a408584ccb/aws-ec2-assign-elastic-ip-0.10.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-WDGYQh/aws-ec2-assign-elastic-ip/setup.py", line 12, in <module>
        with open('README.md', 'r') as fh:
    IOError: [Errno 2] No such file or directory: 'README.md'
```

Is it old pip? Can you check if it works for you?

**Comment by sebdah** [comment]
Argh

**Comment by sebdah** [comment]
That's what I got for rushing :). Try 0.10.2 please, should be ok.

**Comment by przemyslaw-elias** [comment]
Works flawlessly 👌

**Pull request merged**
